config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  draw :account
  draw :admin
  draw :calendar_management
  draw :first_registration

  draw :course_management
  draw :references

  resources :units do
    member do
      get :courses, defaults: { format: :json }
      get :programs, defaults: { format: :json }
      get :curriculums, defaults: { format: :json }
      get :employees, default: { format: :json }
    end
  end

  resources :users, except: [:new, :create] do
    get 'save_address_from_mernis', on: :member
    get 'save_identity_from_mernis', on: :member
  end

  # public profiles
  get '/profiles', to: 'public_profile#index'
  get '/profiles/:id', to: 'public_profile#show', as: :profiles_show
  get '/profiles/:id/vcard',  to: 'public_profile#vcard', as: :profile_vcard

  scope module: :studies do
    get '/studies', to: 'dashboard#index'
    get '/studies/articles', to: 'articles#index'
    get '/studies/projects', to: 'projects#index'
    get '/studies/certifications', to: 'certifications#index'
  end

  resources :agenda_types, except: :show, module: :committee

  resources :committees, only: :index, controller: 'committee/dashboard' do
    scope module: :committee do
      resources :agendas, except: :show
      resources :meetings
      resources :meeting_agendas, only: [] do
        resources :decisions, except: %i[index destroy]
      end
    end
  end
end

app/models/unit.rb
# frozen_string_literal: true

class Unit < ApplicationRecord
  # search
  include PgSearch
  include DynamicSearch

  pg_search_scope(
    :search,
    against: %i[name yoksis_id detsis_id abbreviation],
    using: { tsearch: { prefix: true } }
  )

  # dynamic_search
  search_keys :duration, :unit_status_id, :unit_instruction_type_id, :unit_instruction_language_id

  # callbacks
  before_save :cache_ancestry
  before_validation { self.name = name.capitalize_turkish if name }

  # relations
  has_ancestry
  belongs_to :district
  belongs_to :unit_status
  belongs_to :unit_type, optional: true
  belongs_to :unit_instruction_type, optional: true
  belongs_to :unit_instruction_language, optional: true
  belongs_to :university_type, optional: true
  has_many :duties, dependent: :destroy
  has_many :employees, through: :duties
  has_many :students, dependent: :nullify
  has_many :users, through: :employees
  has_many :positions, through: :duties
  has_many :administrative_functions, through: :duties
  has_many :agendas, dependent: :nullify
  has_many :meetings, dependent: :nullify, class_name: 'CommitteeMeeting'
  has_many :meeting_agendas, through: :meetings
  has_many :decisions, through: :meeting_agendas, class_name: 'CommitteeDecision'
  has_many :courses, dependent: :nullify
  has_many :course_groups, dependent: :nullify
  has_many :curriculum_programs, dependent: :destroy
  has_many :curriculums, through: :curriculum_programs
  has_many :managed_curriculums, dependent: :destroy, class_name: 'Curriculum'
  has_many :registration_documents, dependent: :destroy
  has_many :prospective_students, dependent: :destroy
  has_many :available_courses, dependent: :destroy
  has_many :unit_calendars, dependent: :destroy
  has_many :calendars, through: :unit_calendars

  # validations
  validates :name, presence: true,
                   uniqueness: { scope: %i[yoksis_id detsis_id unit_status] }, length: { maximum: 255 }
  validates :abbreviation, length: { maximum: 255 }
  validates :code, length: { maximum: 255 }
  validates :yoksis_id, allow_nil: true, uniqueness: true, numericality: { only_integer: true }, length: { is: 6 }
  validates :detsis_id, allow_nil: true, uniqueness: true, numericality: { only_integer: true }, length: { is: 8 }
  validates :osym_id, allow_nil: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :foet_code, allow_nil: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :duration, allow_nil: true, numericality: { only_integer: true }, inclusion: 1..8

  # scopes
  scope :active,                 -> { where(unit_status: UnitStatus.active) }
  scope :administratives,        -> { where(unit_type: UnitType.administrative) }
  scope :committees,             -> { where(unit_type: UnitType.committee) }
  scope :departments,            -> { where(unit_type: UnitType.department) }
  scope :faculties,              -> { where(unit_type: UnitType.faculty) }
  scope :graduate_programs,      -> { where(unit_type: UnitType.graduate_program) }
  scope :institutes,             -> { where(unit_type: UnitType.institute) }
  scope :majors,                 -> { where(unit_type: UnitType.major) }
  scope :others,                 -> { where(unit_type: UnitType.other) }
  scope :partially_passive,      -> { where(unit_status: UnitStatus.partially_passive) }
  scope :programs,               -> { where(unit_type: UnitType.program) }
  scope :research_centers,       -> { where(unit_type: UnitType.research_center) }
  scope :senates,                -> { where(unit_type: UnitType.senate) }
  scope :undergraduate_programs, -> { where(unit_type: UnitType.undergraduate_program) }
  scope :without_programs,       -> { where.not(unit_type: UnitType.program) }

  scope :academic, -> {
    faculties
      .or(departments)
      .or(majors)
      .or(programs)
      .or(institutes)
  }

  scope :coursable, -> {
    departments
      .or(faculties)
      .or(majors)
      .or(institutes)
      .or(others)
  }

  scope :curriculumable, -> { coursable }

  scope :eventable, -> {
    faculties
      .or(institutes)
      .or(programs)
      .or(research_centers)
      .or(others)
  }

  def cache_ancestry
    parent_names = path.map(&:name)
    self.names_depth_cache = if path.count > 1
                               parent_names.drop(1).reverse.join(' / ')
                             else
                               parent_names.reverse.join(' / ')
                             end
  end

  # custom methods
  def subprograms
    descendants.programs
  end

  def subtree_employees
    Employee.includes(:user, :title).joins(:units, user: :identities)
            .where(units: { id: subtree.active.ids })
  end
end

app/models/unit_type.rb
# frozen_string_literal: true

class UnitType < ApplicationRecord
  include ReferenceCallbacks
  include ReferenceSearch
  include ReferenceValidations

  # enums
  enum group: {
    other: 0,
    faculty: 1,
    department: 2,
    major: 3,
    undergraduate_program: 4,
    graduate_program: 5,
    institute: 6,
    research_center: 7,
    committee: 8,
    administrative: 9
  }

  # scopes
  scope :program, -> { where(group: %w[undergraduate_program graduate_program]) }
  scope :senate, -> { where(name: 'Senato') }

  # relations
  has_many :units, dependent: :nullify

  # validations
  validates :group, allow_nil: true, inclusion: { in: groups.keys }
end

app/models/units/interdisciplinary_department.rb
class InterdisciplinaryDepartment < ApplicationRecord
  belongs_to :institute
end

app/controllers/units_controller.rb
# frozen_string_literal: true

class UnitsController < ApplicationController
  include SearchableModule

  before_action :set_unit, only: %i[edit update destroy show courses programs curriculums employees]

  def index
    units = Unit.includes(
      :unit_status, :unit_instruction_type, :unit_type
    ).order(:name)

    @pagy, @units = pagy(units.dynamic_search(search_params(Unit)))
  end

  def show; end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)
    @unit.save ? redirect_to(@unit, notice: t('.success')) : render(:new)
  end

  def edit; end

  def update
    @unit.update(unit_params) ? redirect_to(@unit, notice: t('.success')) : render(:edit)
  end

  def destroy
    if @unit.destroy
      redirect_to(units_path, notice: t('.success'))
    else
      redirect_to(units_path, alert: t('.warning'))
    end
  end

  def courses
    @courses = @unit.courses.active
  end

  def programs
    @units = @unit.subprograms.active.order(:name)
    render json: @units
  end

  def curriculums
    @curriculums = @unit.managed_curriculums.active.order(:name)
    render json: @curriculums
  end

  def employees
    @employees = Employee.includes(:units, :title, user: :identities)
                         .where(units: { id: @unit.subtree.active.ids })
  end

  private

  def set_unit
    @unit = Unit.find(params[:id])
  end

  def unit_params
    params.require(:unit).permit(
      :name, :yoksis_id, :detsis_id, :foet_code, :founded_at, :duration, :district_id, :parent_id, :unit_status_id,
      :unit_instruction_language_id, :unit_instruction_type_id, :unit_type_id, :university_type_id, :abbreviation,
      :code
    )
  end
end

app/views/units/_form.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='card'>
      <div class='card-header'>
        <%= fa_icon 'calendar' %>
        <strong><%= form_title %></strong>
      </div>
      <div class='card-body'>
        <%= simple_form_for(unit) do |f| %>
          <div class='row'>
            <div class='form-group col-sm-12'>
              <%= f.error_notification %>
            </div>
            <div class='form-group col-sm-12'>
              <%= f.input :name, required: true %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.input :yoksis_id %>
            </div>
           <div class='form-group col-sm-6'>
              <%= f.input :detsis_id %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.input :founded_at, required: true, start_year: Date.today.year - 50 %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.association :unit_status %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.association :unit_instruction_language %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.association :unit_instruction_type %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.input :duration, collection: 1..8 %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.association :unit_type %>
            </div>

            <div class='form-group col-sm-6'>
              <%= f.association :district,
                                collection: City.includes(:districts).order(:name),
                                as: :grouped_select,
                                group_method: :districts,
                                group_label_method: :name,
                                input_html: { id: 'district_list' } %>
            </div>
            <div class='form-group col-sm-6'>
              <%= f.input :parent_id, as: :select,
                                      collection: Unit.partially_passive.or(Unit.active).order(:name),
                                      input_html: { id: 'parent_unit_list' },
                                      label_method: :names_depth_cache %>
            </div>
            <div class='form-group col-sm-12'>
              <%= f.button :submit, class: 'btn btn-outline-success btn-sm' %>
              <%= link_to_back(:back) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'select2' %>

app/views/units/_search.html.erb
<div id="SearchForms" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="Search">
      <h5 class="mb-0">
        <a class="collapsed"
           data-toggle="collapse"
           href="#collapseSearch"
           id="collapseSearchLink"
           aria-expanded="false"
           aria-controls="Search">
          <%= t('search') %>
        </a>
        <div class="float-right">
          <%= link_to t('reset'), units_path, class: 'btn btn-warning btn-sm' %>
        </div>
      </h5>
    </div>
    <div id="collapseSearch"
         class="collapse show"
         role="tabpanel"
         aria-labelledby="Search"
         data-parent="#SearchForms">
      <div class="card-body">
        <%= form_tag units_path, method: :get do %>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <%= label_tag :term, t('smart_search') %>
                <%= text_field_tag :term,
                                   params[:term],
                                   placeholder: t('.smart_search_placeholder'),
                                   class: 'form-control' %>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <%= label_tag :duration, t('.duration') %>
                <%= text_field_tag :duration,
                                   params[:duration],
                                   placeholder: 'Öğretim Süresi (Yıl)',
                                   class: 'form-control' %>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <%= label_tag :unit_status_id, t('.unit_status') %>
                <%= select_tag(:unit_status_id,
                               options_from_collection_for_select(UnitStatus.all, :id, :name, params[:unit_status_id]),
                               include_blank: true,
                               class: 'form-control') %>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <%= label_tag :unit_instruction_language_id, t('.unit_instruction_language') %>
                <%= select_tag(:unit_instruction_language_id,
                               options_from_collection_for_select(UnitInstructionLanguage.all, :id, :name, params[:unit_instruction_language_id]),
                               include_blank: true,
                               class: 'form-control') %>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="form-group">
                <%= label_tag :unit_instruction_type_id, t('.unit_instruction_type') %>
                <%= select_tag(:unit_instruction_type_id,
                               options_from_collection_for_select(UnitInstructionType.all, :id, :name, params[:unit_instruction_type_id]),
                               include_blank: true,
                               class: 'form-control') %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <%= submit_tag t('search'), class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type='text/javascript'>
  $(document).ready(function() {
    $('#unit_status_id, #unit_instruction_language_id, #unit_instruction_type_id').select2();
  });
</script>

app/views/units/_select2.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('#unit_unit_instruction_language_id, #unit_unit_status_id').select2();
    $('#unit_unit_instruction_type_id, #unit_duration').select2();
    $('#unit_unit_type_id, #district_list, #parent_unit_list').select2();
  });
</script>

app/views/units/edit.html.erb
<%= render 'form', unit: @unit, form_title: t('.form_title') %>

app/views/units/index.html.erb
<div class='alert alert-light'>
  <%= link_to_new(t('.new_unit_link'), new_unit_path) %>
</div>

<div class='row'>
  <div class='col-lg-12'>
    <div class='card'>
      <div class='card-header'>
        <%= fa_icon 'align-justify', text: t('.card_header') %>
      </div>
      <div class='card-body'>
        <%= render 'search' %>
        <table class='table table-responsive-sm table-sm'>
          <thead>
            <tr>
              <th><%= t('.name') %></th>
              <th><%= t('.abbreviation') %></th>
              <th><%= t('.unit_type') %></th>
              <th><%= t('.unit_status') %></th>
              <th><%= t('.unit_instruction_type') %></th>
              <th><%= t('actions') %></th>
            </tr>
          </thead>
          <tbody>
            <% @units.each do |unit| %>
              <tr>
                <td><%= link_to(unit.names_depth_cache, unit_path(unit)) %></td>
                <td><%= unit.abbreviation %></td>
                <td><%= unit.unit_type.try(:name) %></td>
                <td><%= unit.unit_status.try(:name) %></td>
                <td><%= unit.unit_instruction_type.try(:name) %></td>
                <td><%= link_to_actions(unit, except: :show) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <nav aria-label='pagination'>
      <ul class='pagination justify-content-center'>
        <%== pagy_bootstrap_nav(@pagy) %>
      </ul>
    </nav>
  </div>
</div>

app/views/units/new.html.erb
<%= render 'form', unit: @unit, form_title: t('.form_title') %>

app/views/units/show.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <div class="card">
      <div class="card-header">
        <%= fa_icon 'university' %><strong><%= @unit.name %></strong>
        <div class="card-header-actions">
          <%= link_to_actions(@unit, except: :show) %>
        </div>
      </div>

      <div class="card-body">
        <table class="table table-responsive-sm">
          <tbody>
            <tr>
              <td><%= t('.abbreviation') %></td>
              <td><%= @unit.abbreviation %></td>
            </tr>
            <tr>
              <td><%= t('.code') %></td>
              <td><%= @unit.code %></td>
            </tr>
            <tr>
              <td><%= t('.parent') %></td>
              <td><%= @unit.parent.try(:name) %></td>
            </tr>
            <tr>
              <td><%= t('.yoksis_id') %></td>
              <td><%= @unit.yoksis_id %></td>
            </tr>
            <tr>
              <td><%= t('.detsis_id') %></td>
              <td><%= @unit.detsis_id %></td>
            </tr>
            <tr>
              <td><%= t('.foet_code') %></td>
              <td><%= @unit.foet_code %></td>
            </tr>
            <tr>
              <td><%= t('.founded_at') %></td>
              <td><%= @unit.founded_at %></td>
            </tr>
            <tr>
              <td><%= t('.duration') %></td>
              <td><%= @unit.duration %></td>
            </tr>
            <tr>
              <td><%= t('.unit_type') %></td>
              <td><%= @unit.unit_type.try(:name) %></td>
            </tr>
            <tr>
              <td><%= t('.district') %></td>
              <td><%= @unit.district.name %> / <%= @unit.district.city.name %></td>
            </tr>
            <tr>
              <td><%= t('.unit_status') %></td>
              <td><%= @unit.unit_status.try(:name) %></td>
            </tr>
            <tr>
              <td><%= t('.unit_instruction_language') %></td>
              <td><%= @unit.unit_instruction_language.try(:name) %></td>
            </tr>
            <tr>
              <td><%= t('.unit_instruction_type') %></td>
              <td><%= @unit.unit_instruction_type.try(:name) %></td>
            </tr>
            <tr>
              <td><%= t('created_at') %></td>
              <td><%= @unit.created_at %></td>
            </tr>
            <tr>
              <td><%= t('updated_at') %></td>
              <td><%= @unit.updated_at %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>